version: '2'
services:
  flask:
    build: collect_local_data
    restart: always
    container_name: flask
    image: flask
    environment:
      - FLASK_APP=app.py
    env_file: config.env
    ports:
      - "5000:5000"
    volumes:
      - ./collect_local_data/src:/app
      - ./collect_local_data/data:/app/data
  influxdb:
    build: influxdb
    restart: always
    container_name: influxdb
    image: influxdb-hackaday
    env_file: config.env
    ports:
      - '8086:8086'
      - '8083:8083'
    volumes:
      - ./influxdb_data:/var/lib/influxdb        
  grafana:
    image: fg2it/grafana-armhf:v4.1.2
    restart: always
    container_name: grafana
    env_file: config.env
    links:
      - influxdb
    ports:
      - '3000:3000'
    depends_on:
      - influxdb
  neurio_influxdb:
    build: neurio_influxdb
    restart: always
    container_name: neurio_influxdb
    image: neurio_influxdb
    env_file: config.env
    links:
      - influxdb
    depends_on:
      - influxdb
    volumes:
      - ./neurio_influxdb/src:/app

