version: '2'
services:
  web:
    build: .
    restart: always
    container_name: flask
    environment:
      - FLASK_APP=app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./data:/app/data

